apiVersion: v1
kind: Service
metadata:
  labels:
    app: Paginationssrv
    service: Paginationssrv
  name: Paginationssrv
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: Paginations